import type { Theme } from 'vitepress';
import DefaultTheme from 'vitepress/theme';
import { onMounted } from 'vue';
import CodePreview from './components/CodePreview.vue';
import ColorTokens from './components/ColorTokens.vue';
import DoItem from './components/DoItem.vue';
import DontItem from './components/DontItem.vue';
import DosDonts from './components/DosDonts.vue';
import ButtonDemo from '../../../../packages/vue/src/atoms/Button/demo.vue';
import DetailsDemo from '../../../../packages/vue/src/atoms/Details/demo.vue';
import IconDemo from '../../../../packages/vue/src/atoms/Icon/demo.vue';
import DateInputDemo from '../../../../packages/vue/src/atoms/DateInput/demo.vue';
import InputDemo from '../../../../packages/vue/src/atoms/Input/demo.vue';
import SelectDemo from '../../../../packages/vue/src/atoms/Select/demo.vue';
import SkipLinkDemo from '../../../../packages/vue/src/atoms/SkipLink/demo.vue';
import SpinnerDemo from '../../../../packages/vue/src/atoms/Spinner/demo.vue';
import ToggleDemo from '../../../../packages/vue/src/atoms/Toggle/demo.vue';
import AutocompleteDemo from '../../../../packages/vue/src/atoms/Autocomplete/demo.vue';
import BadgeDemo from '../../../../packages/vue/src/atoms/Badge/demo.vue';
import AccordionDemo from '../../../../packages/vue/src/molecules/Accordion/demo.vue';
import AddressInputDemo from '../../../../packages/vue/src/molecules/AddressInput/demo.vue';
import AlertDemo from '../../../../packages/vue/src/molecules/Alert/demo.vue';
import AnchorLinksDemo from '../../../../packages/vue/src/molecules/AnchorLinks/demo.vue';
import BreadcrumbDemo from '../../../../packages/vue/src/molecules/Breadcrumb/demo.vue';
import CardDemo from '../../../../packages/vue/src/molecules/Card/demo.vue';
import CheckboxDemo from '../../../../packages/vue/src/atoms/Checkbox/demo.vue';
import CheckboxGroupDemo from '../../../../packages/vue/src/molecules/CheckboxGroup/demo.vue';
import ModalDemo from '../../../../packages/vue/src/molecules/Modal/demo.vue';
import RadioGroupDemo from '../../../../packages/vue/src/molecules/RadioGroup/demo.vue';
import TabsDemo from '../../../../packages/vue/src/molecules/Tabs/demo.vue';
import CookieMessageDemo from '../../../../packages/vue/src/molecules/CookieMessage/demo.vue';
import IconGallery from './components/IconGallery.vue';
import SnackEmbed from './components/SnackEmbed.vue';
import { GT_ICON_REGISTRY_KEY } from '../../../../packages/vue/src/atoms/Icon/types';
import { iconRegistry } from '@grundtone/icons';
import { setupColorPreview } from 'vitepress-plugin-color-preview/client';
import DiagramPreview from 'vitepress-plugin-mermaid-diagram/DiagramPreview.vue';
import 'vitepress-plugin-color-preview/style.css';
import 'vitepress-plugin-mermaid-diagram/diagram-dark.css';
import '@grundtone/design-system/dist/index.css';
import './custom.css';

export default {
  extends: DefaultTheme,
  enhanceApp({ app }) {
    app.provide(GT_ICON_REGISTRY_KEY, iconRegistry);
    app.component('CodePreview', CodePreview);
    app.component('ColorTokens', ColorTokens);
    app.component('DoItem', DoItem);
    app.component('DontItem', DontItem);
    app.component('DosDonts', DosDonts);
    app.component('ButtonDemo', ButtonDemo);
    app.component('IconDemo', IconDemo);
    app.component('DateInputDemo', DateInputDemo);
    app.component('InputDemo', InputDemo);
    app.component('SelectDemo', SelectDemo);
    app.component('SkipLinkDemo', SkipLinkDemo);
    app.component('SpinnerDemo', SpinnerDemo);
    app.component('ToggleDemo', ToggleDemo);
    app.component('AutocompleteDemo', AutocompleteDemo);
    app.component('BadgeDemo', BadgeDemo);
    app.component('AccordionDemo', AccordionDemo);
    app.component('AddressInputDemo', AddressInputDemo);
    app.component('AlertDemo', AlertDemo);
    app.component('DetailsDemo', DetailsDemo);
    app.component('AnchorLinksDemo', AnchorLinksDemo);
    app.component('BreadcrumbDemo', BreadcrumbDemo);
    app.component('CardDemo', CardDemo);
    app.component('CheckboxDemo', CheckboxDemo);
    app.component('CheckboxGroupDemo', CheckboxGroupDemo);
    app.component('ModalDemo', ModalDemo);
    app.component('RadioGroupDemo', RadioGroupDemo);
    app.component('TabsDemo', TabsDemo);
    app.component('CookieMessageDemo', CookieMessageDemo);
    app.component('IconGallery', IconGallery);
    app.component('SnackEmbed', SnackEmbed);
    app.component('DiagramPreview', DiagramPreview);
  },
  setup() {
    onMounted(() => setupColorPreview());
  },
} satisfies Theme;
