/**
 * Generate `packages/tokens-rust/src/generated.rs` from @grundtone/core's
 * default themes — the same tokens→new-surface pattern as @grundtone/email:
 * one source of truth, one codegen step per surface. Change a token in core,
 * re-run this, and the Rust constants the Tauri shell consumes update too.
 *
 * Usage:
 *   pnpm gen:rust-tokens          — (re)write generated.rs
 *   pnpm gen:rust-tokens --check  — exit 1 if generated.rs is out of date
 *                                    (CI drift-gate; keeps TS source and Rust
 *                                    output from silently diverging)
 *
 * Only tokens the NATIVE shell can meaningfully use are emitted: colors
 * (both modes, all semantic keys) and radius/spacing converted to px (f64,
 * 1rem = 16px). Typography/shadows/transitions stay web-only — the webview
 * already gets those through the normal CSS pipeline.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

// core ships CJS+ESM; named ESM imports of the workspace build don't resolve
// under tsx from a root script, so load the CJS entry explicitly.
const require = createRequire(import.meta.url);
const {
  defaultColorPreset,
  defaultColorPresetDark,
  defaultSpacing,
  defaultRadius,
} = require('@grundtone/core') as typeof import('@grundtone/core');

const here = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(here, '../packages/tokens-rust/src/generated.rs');
const checkMode = process.argv.includes('--check');

/** camelCase → SCREAMING_SNAKE for const names, and → snake_case for fields. */
function toSnake(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();
}

/** rem/px CSS lengths → px as f64 (root = 16px). "0" → 0. */
function cssLengthToPx(value: string): number {
  if (value === '0') return 0;
  if (value.endsWith('rem')) return parseFloat(value) * 16;
  if (value.endsWith('px')) return parseFloat(value);
  throw new Error(`Unsupported CSS length for Rust codegen: "${value}"`);
}

/** Rust-identifier-safe key for scale names like "2xl" → "xl2". */
function scaleIdent(key: string): string {
  return /^[0-9]/.test(key) ? `x${key}`.replace(/^x(\d+)(.*)$/, '$2$1') : key;
}

const colorKeys = Object.keys(defaultColorPreset);
const darkKeys = Object.keys(defaultColorPresetDark);
if (JSON.stringify(colorKeys) !== JSON.stringify(darkKeys)) {
  throw new Error(
    'light/dark color presets have diverging keys — fix @grundtone/core first',
  );
}

function colorsStruct(): string {
  const fields = colorKeys
    .map(k => `    pub ${toSnake(k)}: &'static str,`)
    .join('\n');
  return `/// Every semantic color slot grundtone defines, as \`#rrggbb\` hex strings.\n#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub struct Colors {\n${fields}\n}`;
}

function colorsConst(
  name: string,
  doc: string,
  preset: Record<string, string>,
): string {
  const fields = colorKeys
    .map(k => `    ${toSnake(k)}: "${preset[k]}",`)
    .join('\n');
  return `${doc}\npub const ${name}: Colors = Colors {\n${fields}\n};`;
}

function scaleConsts(prefix: string, scale: Record<string, string>): string {
  return Object.entries(scale)
    .map(([k, v]) => {
      const px = cssLengthToPx(v);
      return `/// \`${v}\` (${px}px)\npub const ${prefix}_${scaleIdent(k).toUpperCase()}: f64 = ${px.toFixed(1)};`;
    })
    .join('\n');
}

const header = `// GENERATED by scripts/generate-rust-tokens.ts — DO NOT EDIT.
// Source of truth: @grundtone/core's default themes. Re-run
// \`pnpm gen:rust-tokens\` after changing tokens; CI's --check mode
// fails if this file drifts from the TypeScript source.
#![allow(clippy::excessive_precision)]
`;

const body = [
  header,
  colorsStruct(),
  '',
  colorsConst(
    'LIGHT',
    '/// grundtone default light theme.',
    defaultColorPreset as Record<string, string>,
  ),
  '',
  colorsConst(
    'DARK',
    '/// grundtone default dark theme.',
    defaultColorPresetDark as Record<string, string>,
  ),
  '',
  '// ── Spacing scale (px, 1rem = 16px) ─────────────────────',
  scaleConsts('SPACING', defaultSpacing as Record<string, string>),
  '',
  '// ── Radius scale (px) ───────────────────────────────────',
  scaleConsts('RADIUS', defaultRadius as Record<string, string>),
  '',
].join('\n');

if (checkMode) {
  const current = existsSync(outPath) ? readFileSync(outPath, 'utf8') : '';
  if (current !== body) {
    console.error(
      'generate-rust-tokens: packages/tokens-rust/src/generated.rs is OUT OF DATE ' +
        'with @grundtone/core — run `pnpm gen:rust-tokens` and commit the result.',
    );
    process.exit(1);
  }
  console.log(
    'generate-rust-tokens: generated.rs matches the TypeScript source.',
  );
} else {
  writeFileSync(outPath, body);
  console.log(
    `generate-rust-tokens: wrote ${outPath} (${colorKeys.length} colors × 2 modes).`,
  );
}
