// GENERATED by scripts/generate-rust-tokens.ts — DO NOT EDIT.
// Source of truth: @grundtone/core's default themes. Re-run
// `pnpm gen:rust-tokens` after changing tokens; CI's --check mode
// fails if this file drifts from the TypeScript source.
#![allow(clippy::excessive_precision)]

/// Every semantic color slot grundtone defines. Values are `#rrggbb`/`#rgb`
/// hex or `rgba(r,g,b,a)` strings — both parse via `Rgba::parse`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Colors {
    pub primary: &'static str,
    pub primary_light: &'static str,
    pub primary_dark: &'static str,
    pub on_primary: &'static str,
    pub secondary: &'static str,
    pub secondary_light: &'static str,
    pub secondary_dark: &'static str,
    pub success: &'static str,
    pub success_light: &'static str,
    pub success_dark: &'static str,
    pub warning: &'static str,
    pub warning_light: &'static str,
    pub warning_dark: &'static str,
    pub error: &'static str,
    pub error_light: &'static str,
    pub error_dark: &'static str,
    pub info: &'static str,
    pub info_light: &'static str,
    pub info_dark: &'static str,
    pub background: &'static str,
    pub background_alt: &'static str,
    pub surface: &'static str,
    pub surface_alt: &'static str,
    pub surface_raised: &'static str,
    pub surface_overlay: &'static str,
    pub modal_backdrop: &'static str,
    pub text: &'static str,
    pub text_secondary: &'static str,
    pub text_tertiary: &'static str,
    pub text_inverse: &'static str,
    pub text_placeholder: &'static str,
    pub text_disabled: &'static str,
    pub border_light: &'static str,
    pub border_medium: &'static str,
    pub border_strong: &'static str,
    pub border_inverse: &'static str,
    pub focus: &'static str,
    pub focus_ring: &'static str,
    pub neutral: &'static str,
}

impl Colors {
    /// Every slot's camelCase name, matching grundtone's TypeScript/JSON keys.
    pub const SLOT_NAMES: [&'static str; 39] = [
        "primary",
        "primaryLight",
        "primaryDark",
        "onPrimary",
        "secondary",
        "secondaryLight",
        "secondaryDark",
        "success",
        "successLight",
        "successDark",
        "warning",
        "warningLight",
        "warningDark",
        "error",
        "errorLight",
        "errorDark",
        "info",
        "infoLight",
        "infoDark",
        "background",
        "backgroundAlt",
        "surface",
        "surfaceAlt",
        "surfaceRaised",
        "surfaceOverlay",
        "modalBackdrop",
        "text",
        "textSecondary",
        "textTertiary",
        "textInverse",
        "textPlaceholder",
        "textDisabled",
        "borderLight",
        "borderMedium",
        "borderStrong",
        "borderInverse",
        "focus",
        "focusRing",
        "neutral",
    ];

    /// Look up a slot by its camelCase name (the TypeScript/JSON key).
    pub fn slot(&self, name: &str) -> Option<&'static str> {
        match name {
            "primary" => Some(self.primary),
            "primaryLight" => Some(self.primary_light),
            "primaryDark" => Some(self.primary_dark),
            "onPrimary" => Some(self.on_primary),
            "secondary" => Some(self.secondary),
            "secondaryLight" => Some(self.secondary_light),
            "secondaryDark" => Some(self.secondary_dark),
            "success" => Some(self.success),
            "successLight" => Some(self.success_light),
            "successDark" => Some(self.success_dark),
            "warning" => Some(self.warning),
            "warningLight" => Some(self.warning_light),
            "warningDark" => Some(self.warning_dark),
            "error" => Some(self.error),
            "errorLight" => Some(self.error_light),
            "errorDark" => Some(self.error_dark),
            "info" => Some(self.info),
            "infoLight" => Some(self.info_light),
            "infoDark" => Some(self.info_dark),
            "background" => Some(self.background),
            "backgroundAlt" => Some(self.background_alt),
            "surface" => Some(self.surface),
            "surfaceAlt" => Some(self.surface_alt),
            "surfaceRaised" => Some(self.surface_raised),
            "surfaceOverlay" => Some(self.surface_overlay),
            "modalBackdrop" => Some(self.modal_backdrop),
            "text" => Some(self.text),
            "textSecondary" => Some(self.text_secondary),
            "textTertiary" => Some(self.text_tertiary),
            "textInverse" => Some(self.text_inverse),
            "textPlaceholder" => Some(self.text_placeholder),
            "textDisabled" => Some(self.text_disabled),
            "borderLight" => Some(self.border_light),
            "borderMedium" => Some(self.border_medium),
            "borderStrong" => Some(self.border_strong),
            "borderInverse" => Some(self.border_inverse),
            "focus" => Some(self.focus),
            "focusRing" => Some(self.focus_ring),
            "neutral" => Some(self.neutral),
            _ => None,
        }
    }
}

/// grundtone default light theme.
pub const LIGHT: Colors = Colors {
    primary: "#0059b3",
    primary_light: "#3381cc",
    primary_dark: "#003a7a",
    on_primary: "#ffffff",
    secondary: "#e9ecef",
    secondary_light: "#f8f9fa",
    secondary_dark: "#dee2e6",
    success: "#198754",
    success_light: "#d1e7dd",
    success_dark: "#146c43",
    warning: "#ffc107",
    warning_light: "#fff3cd",
    warning_dark: "#cc9a06",
    error: "#dc3545",
    error_light: "#f8d7da",
    error_dark: "#b02a37",
    info: "#0dcaf0",
    info_light: "#cff4fc",
    info_dark: "#0aa2c0",
    background: "#ffffff",
    background_alt: "#fafafa",
    surface: "#f8f9fa",
    surface_alt: "#f0f1f2",
    surface_raised: "#ffffff",
    surface_overlay: "rgba(255,255,255,0.95)",
    modal_backdrop: "rgba(0,0,0,0.5)",
    text: "#212529",
    text_secondary: "#6c757d",
    text_tertiary: "#adb5bd",
    text_inverse: "#ffffff",
    text_placeholder: "#a3a3a3",
    text_disabled: "#d4d4d4",
    border_light: "#dee2e6",
    border_medium: "#ced4da",
    border_strong: "#adb5bd",
    border_inverse: "rgba(255,255,255,0.2)",
    focus: "#0059b3",
    focus_ring: "rgba(0,89,179,0.25)",
    neutral: "#6c757d",
};

/// grundtone default dark theme.
pub const DARK: Colors = Colors {
    primary: "#4dabf7",
    primary_light: "#74c0fc",
    primary_dark: "#339af0",
    on_primary: "#121212",
    secondary: "#343a40",
    secondary_light: "#495057",
    secondary_dark: "#2b3035",
    success: "#51cf66",
    success_light: "#1a3d20",
    success_dark: "#40c057",
    warning: "#ffd43b",
    warning_light: "#3d3a1a",
    warning_dark: "#fab005",
    error: "#ff6b6b",
    error_light: "#3d1a1c",
    error_dark: "#fa5252",
    info: "#4dabf7",
    info_light: "#1a2e3d",
    info_dark: "#339af0",
    background: "#121212",
    background_alt: "#1a1a1a",
    surface: "#1e1e1e",
    surface_alt: "#252525",
    surface_raised: "#2a2a2a",
    surface_overlay: "rgba(30,30,30,0.95)",
    modal_backdrop: "rgba(0,0,0,0.7)",
    text: "#ffffff",
    text_secondary: "#b0b0b0",
    text_tertiary: "#808080",
    text_inverse: "#121212",
    text_placeholder: "#666666",
    text_disabled: "#4a4a4a",
    border_light: "#404040",
    border_medium: "#505050",
    border_strong: "#606060",
    border_inverse: "rgba(0,0,0,0.3)",
    focus: "#4dabf7",
    focus_ring: "rgba(77,171,247,0.25)",
    neutral: "#9e9e9e",
};

// ── Spacing scale (px, 1rem = 16px) ─────────────────────
/// `0.25rem` (4px)
pub const SPACING_XS: f64 = 4.0;
/// `0.5rem` (8px)
pub const SPACING_SM: f64 = 8.0;
/// `1rem` (16px)
pub const SPACING_MD: f64 = 16.0;
/// `1.5rem` (24px)
pub const SPACING_LG: f64 = 24.0;
/// `2rem` (32px)
pub const SPACING_XL: f64 = 32.0;
/// `3rem` (48px)
pub const SPACING_XL2: f64 = 48.0;
/// `4rem` (64px)
pub const SPACING_XL3: f64 = 64.0;
/// `6rem` (96px)
pub const SPACING_XL4: f64 = 96.0;

// ── Radius scale (px) ───────────────────────────────────
/// `0` (0px)
pub const RADIUS_NONE: f64 = 0.0;
/// `0.125rem` (2px)
pub const RADIUS_XS: f64 = 2.0;
/// `0.25rem` (4px)
pub const RADIUS_SM: f64 = 4.0;
/// `0.375rem` (6px)
pub const RADIUS_MD: f64 = 6.0;
/// `0.5rem` (8px)
pub const RADIUS_LG: f64 = 8.0;
/// `0.75rem` (12px)
pub const RADIUS_XL: f64 = 12.0;
/// `1rem` (16px)
pub const RADIUS_XL2: f64 = 16.0;
/// `1.5rem` (24px)
pub const RADIUS_XL3: f64 = 24.0;
/// `9999px` (9999px)
pub const RADIUS_FULL: f64 = 9999.0;
